compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@emotion/babel-preset-css-prop@*":
    dependencies:
      "@babel/core": "*"
  eslint-module-utils@*:
    peerDependencies:
      "@typescript-eslint/parser": "*"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
